name: Run Reusable Workflow (underworked)
run-name: ${{ github.actor }} run builds 🚀
on: [ workflow_dispatch ]
jobs:
  run-prod-vpc-deploy:
    uses: ./.github/workflows/deploy-aws-vpc.yml
    with:
      env-type: prod