AWSTemplateFormatVersion: "2010-09-09"
Description: Testing of creation by cloudformation VPC

Parameters:
  EnvType:
    Description: This parameter describes the type of environment (dev,test,prod)
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: must be one of three valid values

Resources:
  PacePlannerVpc:
    Type: AWS::EC2::VPC
    DeletionPolicy: Delete
    Properties:
      CidrBlock: "10.0.0.0/20"
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${EnvType}-pace-planner-cf-vpc"
  PacePlannerSubnet1:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Delete
    Properties:
      VpcId: !Ref PacePlannerVpc
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.1.0/24"
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${EnvType}-pace-planner-cf-us-east-1a"
  PacePlannerSubnet2:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Delete
    Properties:
      VpcId: !Ref PacePlannerVpc
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.0.2.0/24"
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${EnvType}-pace-planner-cf-us-east-1b"
  PacePlannerInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${EnvType}-pace-planner-cf-ig"
  PacePlannerGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PacePlannerVpc
      InternetGatewayId: !Ref PacePlannerInternetGateway
  PacePlannerRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PacePlannerVpc
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${EnvType}-PacePlannerRouteTable"
  RouteForGateway:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PacePlannerRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref PacePlannerInternetGateway
  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PacePlannerRouteTable
      SubnetId: !Ref PacePlannerSubnet1

Outputs:
  TypeEnv:
    Description: Name of env
    Value: ${EnvType}