name: Build Docker Image and send to DockerHub
run-name: ${{ github.actor }} run builds 🚀
on: [ workflow_dispatch ]
jobs:
  Create-docker-image-and-send-to-DockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as a variable NOW_SUFFIX
        run: echo "NOW_SUFFIX=$(date +'%Y%m%dT%H%M')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: marcinzc/pace-planner:${{ env.NOW_SUFFIX }}