name: Build Pace Planner Image
run-name: ${{ github.actor }} run builds 🚀
on: [workflow_dispatch]
jobs:
  Create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as a variable NOW_SUFFIX
        run: echo "NOW_SUFFIX=$(date +'%Y%m%dT%H%M')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW_SUFFIX # Gives "2022-12-11T01:42:20"