name: Build infrastructure AWS and deploy app on EBS
run-name: ${{ github.actor }} run builds 🚀

on:
  workflow_dispatch:
    inputs:
      S3_NAME_STACK:
        description: "Name of S3 cloudformation stack"
        type: string
        required: true
      VPC_NAME_STACK:
        description: "Name of VPC cloudformation stack"
        type: string
        required: true
      ENV_TYPE:
        description: "Environment type"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  SetVariable:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.setTagId.outputs.imageTag }}
    steps:
      - name: Set tag
        id: setTagId
        run: echo "imageTag=$(date +'%Y%m%dT%H%M')" >> "$GITHUB_OUTPUT"

  ShowImageTag:
    needs: SetVariable
    runs-on: ubuntu-latest
    steps:
      - name: Show image tag
        run: echo IMAGE-TAG ${{ needs.SetVariable.outputs.IMAGE_TAG }}

  BuildDockerImageAndPushToECR:
    needs:
      - SetVariable
    uses: ./.github/workflows/reuse-build-docker-images-send-to-AWS-ECR.yml
    with:
      IMAGE_TAG: ${{ needs.SetVariable.outputs.IMAGE_TAG }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

  CreateInfraVPC:
    needs:
      - BuildDockerImageAndPushToECR
    uses: ./.github/workflows/reuse-deploy-vpc.yml
    with:
      STACK_VPC: ${{ inputs.VPC_NAME_STACK }}
      ENV_TYPE: ${{ inputs.ENV_TYPE }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  CreateInfraS3:
    needs:
      - CreateInfraVPC
    uses: ./.github/workflows/reuse-deploy-s3.yml
    with:
      STACK_S3: ${{ inputs.S3_NAME_STACK }}
      ENV_TYPE: ${{ inputs.ENV_TYPE }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}