name: Build infrastructure AWS and deploy app on EBS
run-name: ${{ github.actor }} run builds 🚀

on: [ workflow_dispatch ]

jobs:
  SetVariable:
    runs-on: ubuntu-latest
    outputs:
      IMAGE-TAG: ${{ steps.setTagId.outouts.imageTag }}
    steps:
      - name: Set tag
        id: setTagId
        run: echo "imageTag=$(date +'%Y%m%dT%H%M')" >> $GITHUB_OUTPUT

  BuildDockerImageAndPushToECR:
    needs:
      - SetVariable
    uses: ./.github/workflows/reuse-build-docker-images-send-to-AWS-ECR.yml
    with:
      IMAGE_TAG: ${{ needs.SetVariable.outputs.IMAGE-TAG }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

