name: Build infrastructure AWS and deploy app on EBS
run-name: ${{ github.actor }} run builds 🚀

on: [ workflow_dispatch ]

jobs:
  SetVariable:
    runs-on: ubuntu-latest
    outputs:
      imageOutput: ${{ steps.setTagId.outputs.imageTag }}
    steps:
      - name: Set tag
        id: setTagId
        run: echo "imageTag=$(date +'%Y%m%dT%H%M')" >> "$GITHUB_OUTPUT"

  ShowImageTag:
    needs: SetVariable
    runs-on: ubuntu-latest
    steps:
      - name: Show registry
        run: echo IMAGE-TAG ${{ needs.SetVariable.outputs.imageOutput }}
