name: Deploy AWS VPC REUSE
run-name: ${{ github.actor }} run builds 🚀

on:
  workflow_call:
    inputs:
      STACK_VPC:
        required: true
        type: string
      ENV_TYPE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  Validate-cf-file:
    uses: ./.github/workflows/reuse-validate-cf-lint.yml
    with:
      CF_FILE: deploy-env-and-app.yml

  Deploy-VPC:
    runs-on: ubuntu-latest
    needs:
      - Validate-cf-file
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy VPC
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: ${{ inputs.STACK_VPC }}
          template: infrastructure/pace-planner-vpc.yaml
          parameter-overrides: "EnvType=${{ inputs.ENV_TYPE }}"
          no-fail-on-empty-changeset: "1"