name: Lint CloudFormation Templates
run-name: ${{ github.actor }} run builds 🚀

on:
  workflow_call:
    inputs:
      CF_FILE:
        required: true
        type: string
        description: Put the name of cloud formation file

jobs:
  Cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Testing with CFN Lint Command
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: "cfn-lint -t ./infrastructure/${{inputs.CF_FILE}}"